---
default_stages: [commit, push]
default_language_version:
  python: python3
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ check --fix ]
      # Run the formatter.
      - id: ruff-format