[project]
name = "ha-button-plus"
dynamic = ["version"]

dependencies = [
  "homeassistant",
  "pre-commit",
  "packaging"
]

[tool.setuptools]
py-modules = ["custom_components"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]