long_press:
  description: Long press of a button on a Button+
  target:
    entity:
      domain: button_plus
release:
    description: Release of a button on a Button+
    target:
        entity:
          domain: button_plus
